#map_type: costmap
#transform_tolerance: 0.5
#obstacle_range: 2.5
#max_obstacle_height: 2.0
#raytrace_range: 3.0
#inscribed_radius: 0.35
#circumscribed_radius: 0.4
#inflation_radius: 0.1
#cost_scaling_factor: 15.0
#lethal_cost_threshold: 100
obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.3
inflation_radius: 0.1

observation_sources: laser_scan_sensor

base_scan: {sensor_frame: camera_depth_frame_notilt, data_type: LaserScan, topic: /scan_reduced, marking: true, clearing: true}

obstacle_layer: {enable: true, lethal_cost_threshold: 100, track_unknown_space: true, unknown_cost_value: -1}
