obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.3
inflation_radius: 0.1

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame_notilt, data_type: LaserScan, topic: /scan_reduced, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: camera_depth_frame_notilt, data_type: PointCloud2, topic: /camera/depth/points, marking: true, clearing: true}

obstacle_layer: {enable: true, lethal_cost_threshold: 100, track_unknown_space: true, unknown_cost_value: -1}
